version: "3.3"
services:
  front:
    build: .
    command: [ "main:app", "--reload", "--host", "0.0.0.0" ]
    restart: always
    volumes:
      - .:/work
    ports:
      - "3000:8000"
    environment:
      HOSTS_PATH: "/work/hosts.yml"
      SLACK_WEBHOOK: ""
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # mongo-seed:
  #   image: mongo:5.0
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ./mongo_init_d:/dump:ro
  #   command: [ "/bin/bash", "/dump/setup.sh" ]
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
