apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      ecoman: crawler
  template:
    metadata:
      labels:
        ecoman: crawler
    spec:
      containers:
        - name: crawler-container
          image: ghcr.io/cdsl-research/ecoman/crawler:master-9ae0608
          volumeMounts:
            - name: privkey-volume
              mountPath: /keys
              readOnly: true
            - name: hosts-config-volume
              mountPath: /config
              readOnly: true
          env:
            - name: MONGO_USER
              value: root
            - name: MONGO_PASSWORD
              value: password
            - name: MONGO_HOST
              value: mongo-service
            - name: HOSTS_PATH
              value: /config/hosts.yml
      volumes:
        - name: privkey-volume
          secret:
            secretName: priv-key
            items:
              - key: id_rsa
                path: id_rsa
                mode: 0400
        - name: hosts-config-volume
          configMap:
            name: hosts-config
