apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-ecoman
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecoman
  template:
    metadata:
      labels:
        app: ecoman
    spec:
      containers:
        - name: ecoman-container
          image: tomoyk/ecoman:v1.0
          volumeMounts:
            # From file
            - name: secret-volume
              mountPath: /config
          ports:
            - containerPort: 3300
          env:
            # From literal
            - name: SLACK_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: ecoman-secret-vars
                  key: slack-webhook
                  optional: true
      volumes:
        - name: secret-volume
          secret:
            secretName: ecoman-secret-config
            items:
            - key: ../hosts.yaml
              path: hosts.yaml
              mode: 0400
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ecoman
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 3310
      targetPort: 3300
  selector:
    app: ecoman
