---
apiVersion: v1
kind: Service
metadata:
  name: ecoman-executor-svc
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8000
      targetPort: 8000
  selector:
    ecoman: dashboard