apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    db: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        db: mongo
    spec:
      containers:
        - name: mongo-container
          image: mongo:5.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongo
            # You shoud use SECRET
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: ecoman
          volumeMounts:
            - name: mongo-volv
              mountPath: /data/db
          livenessProbe:
            exec:
              command:
                - ls
                - /data/db/lost+found
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 4
      volumes:
        - name: mongo-volv
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: ClusterIP
  selector:
    db: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

