apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-oauth2proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oauth2proxy
  template:
    metadata:
      labels:
        app: oauth2proxy
    spec:
      containers:
        - name: oauth2-container
          image: bitnami/oauth2-proxy:6-debian-10
          args: ["--config", "/path/to/oauth2-proxy.cfg"]
          ports:
            - containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: svc-oauth2proxy
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 4190
      targetPort: 4180
  selector:
    app: ecoman
