name: Image Build

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        target:
          [
            "crawler",
            "dashboard",
            "executor",
          ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag for master
        run: |
          COMMITID=$(git rev-parse --short ${{ github.sha }} | cut -c1-7)
          CUR_BRANCH=$(git symbolic-ref --short HEAD)
          echo "DOCKER_TAG=${CUR_BRANCH}-${COMMITID}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.target }}/Dockerfile
          push: true
          tags: ghcr.io/cdsl-research/ecoman/${{ matrix.target }}:${{ env.DOCKER_TAG }}