name: Image Build

on:
  release:
    types: [published]
jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        target: ["crawler", "dashboard", "executor"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.target }}/Dockerfile
          push: true
          tags: ghcr.io/cdsl-research/ecoman/${{ matrix.target }}:$GITHUB_REF_NAME
